services:
  api:
    build:
      context: .
      dockerfile: /groceries-api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_KEY=${API_KEY}
      - DI_ENDPOINT=${DI_ENDPOINT}
      - DI_KEY=${DI_KEY}
    volumes:
      - db-data:/app/groceries-api/db/data
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - API_GROCERIES_URL=http://api:3000/api/v1
      - API_TOKEN=${API_TOKEN}
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db-data: